In [1]:
import numpy as np
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("IRIS DATASET SHAPE: {}".format(iris_dataset.data.shape))

IRIS DATASET SHAPE: (150, 4)


#### Dividir datos entrenamiento y test

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [3]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

X_train shape: (112, 4)
y_train shape: (112,)


In [4]:
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_test shape: (38, 4)
y_test shape: (38,)


#### Construyendo nuestro modelo

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

### Entrenar nuestro modelo

In [6]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

#### Realizar predicciones con nuevos datos de entrada

In [7]:
prediction = knn.predict(np.array([[5, 2.9, 1, 0.2]]))
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
       iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


#### Evaluar el modelo sobre los datos de test

In [8]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [9]:
print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))

Test set score: 0.97


#### Accuracy Score

In [10]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.973684210526


In [11]:
from sklearn.cross_validation import cross_val_score

scores = cross_val_score(knn, X_test, y_test)
print(scores)
scores.mean()

[ 1.          0.91666667  0.91666667]


/home/jmoc/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


0.94444444444444431

#### Matriz de confusion

In [12]:
from sklearn.metrics import confusion_matrix

matriz_confusion = confusion_matrix(y_test,y_pred)
print(matriz_confusion)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


#### Resumen

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))

Test set score: 0.97
