# NumPy

NumPy es el paquete fundamental para la computación científica con Python.

Documentación: <a>http://www.numpy.org/</a>

In [1]:
from numpy import *

In [2]:
# declarar un vector usando una lista como argumento
v = array([1,2,3,4])
v

array([1, 2, 3, 4])

In [3]:
# declarar una matriz usando listas como argumento
M = array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [4]:
# obtener los tipos de datos del vector y la matriz
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [5]:
#tamaño de la matriz
M.size

4

In [39]:
#dimensiones de la matriz
M.ndim

2

In [40]:
#acceder a elementos del vector y la matriz
v[0], M[1,1]

(1, 4)

In [41]:
# asignar nuevo valor
M[0,0] = 7
M

array([[7, 2],
       [3, 4]])

In [6]:
# crear un vector a partir de los argumentos: start, stop, step
x = arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [28]:
from numpy import random

In [31]:
random.rand(5,5)

array([[ 0.19183488,  0.08252177,  0.38686259,  0.91242356,  0.91547728],
       [ 0.4002033 ,  0.77375428,  0.59362568,  0.7423403 ,  0.61288176],
       [ 0.95564079,  0.88195676,  0.10366903,  0.02757606,  0.59496225],
       [ 0.55826956,  0.77344331,  0.06699593,  0.088787  ,  0.59777844],
       [ 0.85858718,  0.2922641 ,  0.44981689,  0.77775838,  0.3626717 ]])

In [37]:
# normal distribution
random.randn(10,5)

array([[-0.22100838, -0.87828915, -0.04272874, -0.03100701,  0.21576789],
       [ 1.03988904, -0.44272654,  1.08464139,  0.30114395, -1.03579252],
       [ 0.06840035, -0.82811075,  2.19108715, -0.79324551,  0.37779913],
       [ 0.27081227, -1.37259206, -1.01128954, -0.73789937, -0.40879036],
       [ 0.77732917,  0.59450767, -1.10745492, -0.89565037, -0.27842441],
       [ 0.0322223 , -0.3121866 , -0.39460425,  0.12443796, -0.17314675],
       [-2.09904222, -0.5949711 , -0.28637331,  1.39549542,  0.27613789],
       [ 0.11758203, -0.65407905,  0.81003328, -2.52534355, -0.46627344],
       [-0.00300084,  0.84761769,  1.09240243, -0.28503987,  2.32031562],
       [ 0.57788922, -0.1660361 , -0.75670826,  0.20477864, -0.86045209]])

In [33]:
#matriz diagonal
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [47]:
# rango dentro de un array
A = array([1,2,3,4,5])
A[0:2]

array([1, 2])

In [51]:
#matriz 5x5 con bucle for
A = array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [53]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [54]:
# index masking
B = array([n for n in range(5)])
row_mask = array([True, False, True, False, False])
B[row_mask]

array([0, 2])

### Linear Algebra

In [55]:
v1 = arange(0, 5)

In [56]:
v1 + 2

array([2, 3, 4, 5, 6])

In [57]:
v1 * 2

array([0, 2, 4, 6, 8])

In [58]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [59]:
#producto escalar
dot(v1, v1)

30

In [60]:
dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [61]:
M = matrix(A)
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [67]:
v = array([1, 2, 3])
w = array([5, 6, 7])

In [68]:
concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6, 7])